<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="0" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Surefire suite" duration-ms="9045" started-at="2018-04-13T11:00:04Z" finished-at="2018-04-13T11:00:13Z">
    <groups>
    </groups>
    <test name="Surefire test" duration-ms="9045" started-at="2018-04-13T11:00:04Z" finished-at="2018-04-13T11:00:13Z">
      <class name="SearchingTest">
        <test-method status="FAIL" signature="Initialize()[pri:0, instance:SearchingTest@77d2e85]" name="Initialize" is-config="true" duration-ms="0" started-at="2018-04-13T16:00:04Z" finished-at="2018-04-13T16:00:04Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [РЇРЅРґРµРєСЃ.РњР°СЂРєРµС‚ вЂ” РІС‹Р±РѕСЂ Рё РїРѕРєСѓРїРєР° С‚РѕРІР°СЂРѕРІ РёР· РїСЂРѕРІРµСЂРµРЅРЅС‹С… РёРЅС‚РµСЂРЅРµС‚-РјР°РіР°Р·РёРЅРѕРІ] but found [Яндекс.Маркет — выбор и покупка товаров из проверенных интернет-магазинов]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [РЇРЅРґРµРєСЃ.РњР°СЂРєРµС‚ вЂ” РІС‹Р±РѕСЂ Рё РїРѕРєСѓРїРєР° С‚РѕРІР°СЂРѕРІ РёР· РїСЂРѕРІРµСЂРµРЅРЅС‹С… РёРЅС‚РµСЂРЅРµС‚-РјР°РіР°Р·РёРЅРѕРІ] but found [Яндекс.Маркет — выбор и покупка товаров из проверенных интернет-магазинов]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at SearchingTest.Initialize(SearchingTest.java:25)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:217)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:144)
	at org.testng.TestRunner.beforeRun(TestRunner.java:634)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:135)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:112)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Initialize -->
        <test-method status="SKIP" signature="CheckSearching()[pri:0, instance:SearchingTest@77d2e85]" name="CheckSearching" duration-ms="57" started-at="2018-04-13T16:00:13Z" finished-at="2018-04-13T16:00:13Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [РЇРЅРґРµРєСЃ.РњР°СЂРєРµС‚ вЂ” РІС‹Р±РѕСЂ Рё РїРѕРєСѓРїРєР° С‚РѕРІР°СЂРѕРІ РёР· РїСЂРѕРІРµСЂРµРЅРЅС‹С… РёРЅС‚РµСЂРЅРµС‚-РјР°РіР°Р·РёРЅРѕРІ] but found [Яндекс.Маркет — выбор и покупка товаров из проверенных интернет-магазинов]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [РЇРЅРґРµРєСЃ.РњР°СЂРєРµС‚ вЂ” РІС‹Р±РѕСЂ Рё РїРѕРєСѓРїРєР° С‚РѕРІР°СЂРѕРІ РёР· РїСЂРѕРІРµСЂРµРЅРЅС‹С… РёРЅС‚РµСЂРЅРµС‚-РјР°РіР°Р·РёРЅРѕРІ] but found [Яндекс.Маркет — выбор и покупка товаров из проверенных интернет-магазинов]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at SearchingTest.Initialize(SearchingTest.java:25)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:217)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:144)
	at org.testng.TestRunner.beforeRun(TestRunner.java:634)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:135)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:112)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CheckSearching -->
        <test-method status="SKIP" signature="Shutdown()[pri:0, instance:SearchingTest@77d2e85]" name="Shutdown" is-config="true" duration-ms="0" started-at="2018-04-13T16:00:13Z" finished-at="2018-04-13T16:00:13Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Shutdown -->
      </class> <!-- SearchingTest -->
    </test> <!-- Surefire test -->
  </suite> <!-- Surefire suite -->
</testng-results>
